# Generated by Django 4.0.4 on 2022-05-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('göndericiMail', models.CharField(max_length=50)),
                ('göndericiAdi', models.CharField(max_length=50)),
                ('göndericiTelefon', models.CharField(max_length=50)),
                ('göndericiAciklama', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paylasim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('göndericiAdi', models.CharField(max_length=100)),
                ('gönderiKonu', models.CharField(max_length=100)),
                ('gönderiAciklama', models.TextField()),
                ('gönderiDurumu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
