# Generated by Django 4.0.4 on 2022-05-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ariza',
            old_name='göndericiAciklama',
            new_name='gelenAciklama',
        ),
        migrations.RenameField(
            model_name='ariza',
            old_name='göndericiAdi',
            new_name='gelenAdSoyad',
        ),
        migrations.RenameField(
            model_name='ariza',
            old_name='göndericiMail',
            new_name='gelenMail',
        ),
        migrations.RenameField(
            model_name='ariza',
            old_name='göndericiTelefon',
            new_name='gelenTelefon',
        ),
    ]
