# Generated by Django 4.0.4 on 2022-05-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_paylasim_cameurunumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paylasim',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
