# Generated by Django 4.0.4 on 2022-05-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ariza_slug_paylasim_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='gelenKonu',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
