# Generated by Django 4.0.4 on 2022-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ariza_gelenkonu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='gelenKonu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paylasim',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
