# Generated by Django 4.0.4 on 2022-05-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_paylasim_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='paylasim',
            name='gönderiFoto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paylasim',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
