# Generated by Django 4.0.4 on 2022-05-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_paylasim_gönderifoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='gelenFoto',
            field=models.ImageField(blank=True, null=True, upload_to='Arizas'),
        ),
    ]
