# Generated by Django 4.0.4 on 2022-05-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ariza_gelenfoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='gelenFoto',
            field=models.ImageField(upload_to='Arizas'),
        ),
    ]
