# Generated by Django 4.0.4 on 2022-05-31 07:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ariza_gelenfoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='gelenAciklama',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='paylasim',
            name='gönderiAciklama',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
