# Generated by Django 4.0.4 on 2022-05-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ariza_gelenaciklama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='gelenKonu',
            field=models.CharField(max_length=50),
        ),
    ]
