# Generated by Django 4.0.4 on 2022-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ariza_gelenkonu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ariza',
            name='gelenFoto',
        ),
        migrations.AlterField(
            model_name='paylasim',
            name='gönderiFoto',
            field=models.ImageField(upload_to='Paylasim'),
        ),
    ]
