# Generated by Django 4.0.4 on 2022-05-31 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='paylasim',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.category'),
        ),
    ]
