# Generated by Django 4.0.4 on 2022-05-31 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_paylasim_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylasim',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.category'),
        ),
    ]
