# Generated by Django 4.0.4 on 2022-06-04 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_firma_ariza_slug_ariza_firma_bilgi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ariza',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
