# Generated by Django 4.0.4 on 2022-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_alter_paylasim_category_alter_paylasim_gönderifoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='UrunTip',
            field=models.CharField(default='came', max_length=100),
        ),
    ]
