# Generated by Django 4.0.4 on 2022-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_category_uruntip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylasim',
            name='gönderiFoto',
            field=models.ImageField(blank=True, null=True, upload_to='Paylasim'),
        ),
    ]
