# Generated by Django 4.0.4 on 2022-06-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_paylasim_gönderifoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaYetkilisi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaİletisimMail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaİletisimTelefon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paylasim',
            name='gönderiFoto',
            field=models.ImageField(upload_to='Paylasim'),
        ),
    ]
