# Generated by Django 4.0.4 on 2022-06-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_alter_ariza_slug_alter_firma_firmayetkilisi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ariza',
            old_name='Timestamp',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='ariza',
            old_name='last_update',
            new_name='update_time',
        ),
    ]
