# Generated by Django 4.0.4 on 2022-06-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_paylasim_gönderidurumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylasim',
            name='gönderiFoto',
            field=models.ImageField(blank=True, null=True, upload_to='Paylasim'),
        ),
    ]
