# Generated by Django 4.0.5 on 2022-06-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_alter_paylasim_gönderifoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='paylasim',
            name='göndericiUser',
            field=models.CharField(default='tanımsız', max_length=30),
        ),
        migrations.AlterField(
            model_name='paylasim',
            name='gönderiFoto',
            field=models.ImageField(blank=True, null=True, upload_to='Paylasim/'),
        ),
    ]
