# Generated by Django 4.0.4 on 2022-06-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_paylasim_göndericiuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paylasim',
            name='göndericiUser',
        ),
    ]
