# Generated by Django 4.0.4 on 2022-06-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_paylasim_göndericiuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paylasim',
            name='göndericiUser',
        ),
        migrations.AddField(
            model_name='paylasim',
            name='göndericiUser_id',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
