# Generated by Django 4.0.5 on 2022-06-07 09:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_remove_paylasim_göndericiuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='ArizaCozumu',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
