# Generated by Django 4.0.5 on 2022-06-07 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_ariza_arizacozumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='ArizaCozumu',
            field=ckeditor.fields.RichTextField(default='Girilmedi'),
        ),
    ]
