# Generated by Django 4.0.5 on 2022-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_alter_ariza_arizacozumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylasim',
            name='göndericiUser_id',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
