# Generated by Django 4.0.5 on 2022-06-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_alter_paylasim_göndericiuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='Arsivmi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(default='Genel', max_length=100),
        ),
        migrations.AlterField(
            model_name='paylasim',
            name='category',
            field=models.ForeignKey(blank=True, default=9, on_delete=django.db.models.deletion.CASCADE, to='tickets.category'),
        ),
        migrations.AlterField(
            model_name='paylasim',
            name='gönderiFoto',
            field=models.ImageField(blank=True, default='Paylasim/akslogo.png', null=True, upload_to='Paylasim/'),
        ),
    ]
