# Generated by Django 4.0.5 on 2022-06-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_ariza_arsivmi_alter_category_categoryname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paylasim',
            name='göndericiUser_id',
        ),
    ]
