# Generated by Django 4.0.5 on 2022-06-09 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0041_remove_paylasim_göndericiuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paylasim',
            name='göndericiUser_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
