# Generated by Django 4.0.5 on 2022-06-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0042_paylasim_göndericiuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paylasim',
            old_name='göndericiUser_id',
            new_name='göndericiUser',
        ),
    ]
