# Generated by Django 4.0.5 on 2022-06-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_alter_paylasim_göndericiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='firma_bilgi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.firma'),
        ),
    ]
