# Generated by Django 4.0.4 on 2022-06-12 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0046_alter_ariza_firma_bilgi_alter_firma_firmaname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='firma_bilgi',
            field=models.ForeignKey(blank=True, default=19, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.firma'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='gelenAciklama',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paylasim',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.category'),
        ),
        migrations.AlterField(
            model_name='paylasim',
            name='gönderiDurumu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paylasim',
            name='göndericiUser',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
