# Generated by Django 4.0.4 on 2022-06-12 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0048_alter_paylasim_göndericiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylasim',
            name='göndericiUser',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
