# Generated by Django 4.0.4 on 2022-06-12 15:27

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0050_alter_paylasim_göndericiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylasim',
            name='göndericiUser',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
