# Generated by Django 4.0.5 on 2022-06-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_alter_paylasim_göndericiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylasim',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.category'),
        ),
    ]
