# Generated by Django 4.0.5 on 2022-06-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_alter_paylasim_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='firma_bilgi',
            field=models.ForeignKey(blank=True, default=35, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.firma'),
        ),
    ]
