# Generated by Django 4.0.5 on 2022-06-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0053_alter_ariza_firma_bilgi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='gelenTelefon',
            field=models.CharField(max_length=10),
        ),
    ]
