# Generated by Django 4.0.5 on 2022-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0055_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ariza',
            name='ArizaCozumu',
        ),
        migrations.AddField(
            model_name='ariza',
            name='CozumVarMı',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
